### ISSUE TITLE
CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by eungbean1029** [PetMeetingProject/PetMeetServer#4]
## 🍀 내용
- CI/CD 파이프라인 구축
- docker-compose.yml 작성
</br>
</br>

## ✅ TODO
- [ ] CI/CD 파이프라인 구축
- [ ] docker-compose.yml 작성
- [ ] CI/CD 통합 테스트
